# version: 0.2

# phases:
#   install:
#     commands:
#       - echo Installing required packages...
#       - pip install -r requirements.txt -t .  # Install dependencies into the current directory

#   build:
#     commands:
#       - echo Running build...
#       - zip -r search-photo.zip .  # Zipping the function and dependencies

#   post_build:
#     commands:
#       - echo Build completed on `date`

# artifacts:
#   files:
#     - '**/*'  # Output the zipped lambda function package
#   discard-paths: yes  # Discards the directory structure in the artifact


version: 0.2

phases:
  install:
    commands:
      # Install any necessary dependencies
      # e.g., AWS CLI, specific software or libraries required by your Lambda
      - echo Installing source dependencies...
      - pip install -r requirements.txt -t .

  pre_build:
    commands:
      # Pre-build steps like setting up environment variables
      - echo Pre-build phase...

  build:
    commands:
      # Commands to build your Lambda function
      - echo Build started on `date`
      - echo Compiling the Lambda function...
      # Replace with commands to compile/build your Lambda function
      - zip -r search-photos.zip .

  post_build:
    commands:
      # Commands for post-build actions, like copying the build artifacts to S3
      - echo Post-build phase...
      - echo Build completed on `date`

artifacts:
  files:
     - '**/*'
  # Specify the name of the output artifact generated by the build
  name: search-photos-$(date +%Y-%m-%d)

# Optional: specify cache paths to speed up builds
# cache:
#   paths:
#     - '/path/to/cache/directory'




# post_build:
#   commands:
#     - echo This will run even if the build fails.
